url:            http://www.holisticpetcompany.co.uk
name:           The Holistic Pet Company
description:    Natural pet health products
payments:       sales@holisticpetcompany.co.uk
exclude:        [README.md]

prose:
  rooturl: "_posts"
  siteurl: "http://holisticpetcompany.github.io/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "Holly"
      - name: "image"
        field:
          element: "text"
          label: "Image URL"
          value: ""

navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Contact
    url: /contact/

shop:
  shipping: "0"
  products:
    pouch:
      price: "7.99"
      shipping: "1.50"
      shipping_max: "4"
      max: 6

