url:            http://www.holisticpetcompany.co.uk
name:           The Holistic Pet Company
description:    Natural pet health products
payments:       sales@holisticpetcompany.co.uk
exclude:        [README.md]

prose:
  rooturl: "_posts"
  siteurl: "http://holisticpetcompany.github.io/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "Holly"
      - name: "image"
        field:
          element: "text"
          label: "Image URL"
          value: ""

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog/
  - text: Products
    url: /products/
  - text: About
    url: /about/
  - text: Contact
    url: /contact/

shop:
  shipping: "4.50"
  products:
    shampoo-250ml:
      price: "12.00"
      shipping: "0.00"
      max: 3
    tea-tin:
      price: "5.20"
      shipping: "0.00"
      max: 3
    tea-refill:
      price: "3.50"
      shipping: "0.00"
      max: 4
